name: Test All
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x", "16.x"]
        os: [ubuntu-latest, macOS-latest]
    env:
      PROVIDER_URL: "https://api.avax.network/ext/bc/C/rpc"
      BLOCK_NUMBER: 7861179
      CHAIN_ID: 43114
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Yarn Install at Root
        run: yarn install --immutable
      
      - name: Lerna Bootstrap Packages
        run: yarn lerna bootstrap

      - name: Fix Type Issues in Packages
        run: yarn fix

      - name: Run Hardhat Node
        run: yarn fork & sleep 20 # wait 20 seconds for the server to fully initialize

      - name: Test
        run: yarn lerna exec yarn test:ci
